### ISSUE TITLE
Cannot specify alternate endpoint for S3

### ISSUE THREAD

**Issue by pymander** [rightscale/right_aws_api#35]
fake-s3 lists this library as a supported one: https://github.com/jubos/fake-s3/wiki/Supported-Clients 

However, when I try to change endpoints to my local fake-s3 server, I get this error:

```
/var/lib/gems/2.3.0/gems/right_aws_api-0.3.4/lib/cloud/aws/base/helpers/utils.rb:213:in `sign_v4_get_service_and_region': Cannot extract service name from "localhost" host (ArgumentError)
    from /var/lib/gems/2.3.0/gems/right_aws_api-0.3.4/lib/cloud/aws/base/helpers/utils.rb:235:in `sign_v4_signature'
    from /var/lib/gems/2.3.0/gems/right_aws_api-0.3.4/lib/cloud/aws/s3/routines/request_signer.rb:95:in `process'
    from /var/lib/gems/2.3.0/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:346:in `block (2 levels) in process_api_request'
    from /var/lib/gems/2.3.0/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:333:in `each'
    from /var/lib/gems/2.3.0/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:333:in `block in process_api_request'
    from /var/lib/gems/2.3.0/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:326:in `loop'
    from /var/lib/gems/2.3.0/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:326:in `process_api_request'
    from /var/lib/gems/2.3.0/gems/right_aws_api-0.3.4/lib/cloud/aws/s3/manager.rb:403:in `api'
    from (eval):2:in `get'
    from /var/lib/gems/2.3.0/gems/right_cloud_api_base-0.2.3/lib/base/manager.rb:117:in `method_missing'
    from testfails.rb:13:in `<main>'
```

Here is the script I'm using:

```
require "right_aws_api"

key      = "XXXXX"
secret   = "XXXXXXXXXX"
endpoint = 'http://localhost:4567'

options = { :cloud => { :no_dns_buckets => true },
            :multi_thread => false,
            :no_subdomains => true }

s3       = RightScale::CloudApi::AWS::S3::Manager::new(key, secret, endpoint, options)

s3.get
```

**Comment by konstantin-dzreev** [comment]
Hi, It seems that fake-s3 supports the un-maintained right_aws (not right_aws_api) gem: https://github.com/rightscale/right_aws

**Comment by pymander** [comment]
Well, that is a bummer. However, I have also tried this library with other non-Amazon S3-compatible services, and you can't change the endpoint.

Is this library *only* going to support Amazon S3, and not other compatible services?

**Comment by konstantin-dzreev** [comment]
To get a request properly signed (Amazon's signature V4) we have to know the Amazon's region. For most of Amazon services the region name is embedded into the endpoint.

In theory, we could make code change that would allow one to use Amazon compatible services, but there was no request so far as I know, and it may take some time to implement.
