### ISSUE TITLE
Complete show-stopper due to net-http-persistent update v3.0

### ISSUE THREAD

**Issue by mdchaney** [rightscale/right_aws_api#38]
Complete stack trace:

ArgumentError: wrong number of arguments (1 for 0)
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/routines/connection_proxies/net_http_persistent_proxy.rb:92:in `new'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/routines/connection_proxies/net_http_persistent_proxy.rb:92:in `create_new_persistent_connection'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/routines/connection_proxies/net_http_persistent_proxy.rb:61:in `request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/routines/connection_proxy.rb:58:in `block in process'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/routines/routine.rb:79:in `call'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/routines/routine.rb:79:in `with_timer'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/routines/connection_proxy.rb:57:in `process'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:346:in `block (2 levels) in process_api_request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:333:in `each'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:333:in `block in process_api_request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:326:in `loop'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/api_manager.rb:326:in `process_api_request'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_aws_api-0.3.4/lib/cloud/aws/s3/manager.rb:403:in `api'
	from (eval):2:in `head'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/right_cloud_api_base-0.2.3/lib/base/manager.rb:117:in `method_missing'
	from (irb):4
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/railties-4.2.7/lib/rails/commands/console.rb:110:in `start'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/railties-4.2.7/lib/rails/commands/console.rb:9:in `start'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/mdchaney/.rvm/gems/ruby-2.2.4/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'2.2.4

Using Ruby 2.2.4 and right_aws_api 0.3.4 (or 0.2.3).  It looks like they made a change to the method defs from standard args to named args in this commit:

https://github.com/drbrain/net-http-persistent/commit/5d4b76c22dd38d29b6fbc1ed700a2a1c78c5abc4#diff-9da42550715aa09be7174a0babadcad3

**Comment by konstantin-dzreev** [comment]
Confirmed, they've changed contract for new method.
As a quick workaround, count you plz try
```
gem 'net-http-persistent', '2.9.4'
```
in your Gemfile?

**Comment by mdchaney** [comment]
Yes, sorry, meant to point that out before I left.

gem 'net-http-persistent', '~>2.9'
gem 'right_aws_api'

**Comment by konstantin-dzreev** [comment]
right_aws_api v 0.3.5 was released, give it a try plz
If everything works fine then we are closing the issue

**Comment by mdchaney** [comment]
Yes, that works - net-http-persistent is now parked officially at ~>2.9.
